version: '3'

services:
  nginx:
    image: nginx:latest
    ports:
    - '80:80'
    volumes:
    - './nginx:/etc/nginx/conf.d'
    - static-files:/static-files
    depends_on:
    - web

  web:
    build: .
    command: sh run-production.sh
    volumes:
    - static-files:/src/deployment/assets/static
    expose:
    - '8000'

volumes:
  static-files: